on: [push]

jobs:
  semver-action:
    runs-on: ubuntu-latest
    name: semver-action

    steps:
    - uses: actions/checkout@v2
      with:
        repository: stugit/dummy_project
        fetch-depth: 0
  

    - uses: stugit/semver-action@v0.0.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: "true"
